# Generated by Django 6.0.2 on 2026-03-10 04:53

import django.db.models.deletion
import applications.employment.constants
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "work_location",
                    models.CharField(
                        choices=[
                            ("onsite", "Onsite"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                        ],
                        default=applications.employment.constants.WorkLocationType["ONSITE"],
                        max_length=20,
                        verbose_name="work location",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("probation", "Probation"),
                            ("on_leave", "On Leave"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                            ("resigned", "Resigned"),
                        ],
                        default=applications.employment.constants.EmploymentStatus[
                            "PROBATION"
                        ],
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="hire date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employments",
                        to="organization.department",
                        verbose_name="department",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment",
                        to="employee.employee",
                        verbose_name="employee",
                    ),
                ),
                (
                    "job_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employments",
                        to="organization.jobtitle",
                        verbose_name="job title",
                    ),
                ),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="employee.employee",
                        verbose_name="reporting manager",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employment",
                "verbose_name_plural": "Employments",
                "ordering": ["-hire_date"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("fixed_term", "Fixed Term"),
                            ("probationary", "Probationary"),
                            ("internship", "Internship"),
                            ("part_time", "Part Time"),
                            ("freelance", "Freelance"),
                        ],
                        max_length=30,
                        verbose_name="contract type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                ("terms", models.TextField(blank=True, verbose_name="terms")),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contracts/",
                        verbose_name="document",
                    ),
                ),
                (
                    "employment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="employment.employment",
                        verbose_name="employment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "pay_grade",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="pay grade"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="IDR", max_length=10, verbose_name="currency"
                    ),
                ),
                (
                    "payment_frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("bi_weekly", "Bi Weekly"),
                            ("monthly", "Monthly"),
                            ("annual", "Annual"),
                        ],
                        default=applications.employment.constants.PaymentFrequency[
                            "MONTHLY"
                        ],
                        max_length=20,
                        verbose_name="payment frequency",
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="effective date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "employment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_history",
                        to="employment.employment",
                        verbose_name="employment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary",
                "verbose_name_plural": "Salaries",
                "ordering": ["-effective_date"],
            },
        ),
    ]
