# Generated by Django 6.0.2 on 2026-03-06 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0001_initial"),
        ("employee", "0001_initial"),
        ("job_title", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmploymentDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "work_location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="work location",
                    ),
                ),
                (
                    "work_location_type",
                    models.CharField(
                        choices=[
                            ("on_site", "On Site"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="on_site",
                        max_length=20,
                        verbose_name="work location type",
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("intern", "Intern"),
                            ("probation", "Probation"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="employment status",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="department.department",
                        verbose_name="department",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment_detail",
                        to="employee.employee",
                        verbose_name="employee",
                    ),
                ),
                (
                    "job_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="job_title.jobtitle",
                        verbose_name="job title",
                    ),
                ),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="employee.employee",
                        verbose_name="reporting manager",
                    ),
                ),
            ],
            options={
                "verbose_name": "employment detail",
                "verbose_name_plural": "employment details",
            },
        ),
    ]
