# Generated by Django 6.0.2 on 2026-03-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={
                "ordering": ("-start_date",),
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
            },
        ),
        migrations.AlterModelOptions(
            name="employment",
            options={
                "ordering": ("-hire_date",),
                "verbose_name": "Employment",
                "verbose_name_plural": "Employments",
            },
        ),
        migrations.AlterModelOptions(
            name="salary",
            options={
                "ordering": ("-effective_date",),
                "verbose_name": "Salary",
                "verbose_name_plural": "Salaries",
            },
        ),
    ]
