# Generated by Django 6.0.2 on 2026-03-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ("name",),
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterModelOptions(
            name="jobtitle",
            options={
                "ordering": ("name",),
                "verbose_name": "Job Title",
                "verbose_name_plural": "Job Titles",
            },
        ),
    ]
