# Generated by Django 6.0.2 on 2026-03-06 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("fixed_term", "Fixed Term"),
                            ("freelance", "Freelance"),
                            ("internship", "Internship"),
                        ],
                        default="permanent",
                        max_length=20,
                        verbose_name="contract type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                (
                    "terms",
                    models.TextField(blank=True, default="", verbose_name="terms"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="employee.employee",
                        verbose_name="employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "contract",
                "verbose_name_plural": "contracts",
                "ordering": ["-start_date"],
            },
        ),
    ]
