# Generated by Django 6.0.2 on 2026-03-15 08:28

import applications.attendance.constants
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0002_alter_emergencycontact_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual"),
                            ("sick", "Sick"),
                            ("personal", "Personal"),
                            ("maternity", "Maternity"),
                            ("paternity", "Paternity"),
                            ("unpaid", "Unpaid"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="leave type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "total_days",
                    models.PositiveSmallIntegerField(
                        help_text="Number of calendar days covered by this request.",
                        verbose_name="total days",
                    ),
                ),
                ("reason", models.TextField(verbose_name="reason")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default=applications.attendance.constants.LeaveStatus[
                            "PENDING"
                        ],
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "approval_notes",
                    models.TextField(blank=True, verbose_name="approval notes"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reviewed at"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_leave_requests",
                        to="employee.employee",
                        verbose_name="reviewed by",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="employee.employee",
                        verbose_name="employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        default="Standard", max_length=100, verbose_name="schedule name"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="default schedule"),
                ),
                ("monday", models.BooleanField(default=True, verbose_name="Monday")),
                ("tuesday", models.BooleanField(default=True, verbose_name="Tuesday")),
                (
                    "wednesday",
                    models.BooleanField(default=True, verbose_name="Wednesday"),
                ),
                (
                    "thursday",
                    models.BooleanField(default=True, verbose_name="Thursday"),
                ),
                ("friday", models.BooleanField(default=True, verbose_name="Friday")),
                (
                    "saturday",
                    models.BooleanField(default=False, verbose_name="Saturday"),
                ),
                ("sunday", models.BooleanField(default=False, verbose_name="Sunday")),
                (
                    "expected_check_in",
                    models.TimeField(verbose_name="expected check-in"),
                ),
                (
                    "expected_check_out",
                    models.TimeField(verbose_name="expected check-out"),
                ),
                ("effective_from", models.DateField(verbose_name="effective from")),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="effective to"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_schedules",
                        to="employee.employee",
                        verbose_name="employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Schedule",
                "verbose_name_plural": "Work Schedules",
                "ordering": ("-effective_from",),
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("date", models.DateField(verbose_name="date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("half_day", "Half Day"),
                            ("on_leave", "On Leave"),
                            ("holiday", "Holiday"),
                            ("weekend", "Weekend"),
                        ],
                        default=applications.attendance.constants.AttendanceStatus[
                            "PRESENT"
                        ],
                        max_length=30,
                        verbose_name="status",
                    ),
                ),
                (
                    "check_in",
                    models.TimeField(
                        blank=True, null=True, verbose_name="check-in time"
                    ),
                ),
                (
                    "check_out",
                    models.TimeField(
                        blank=True, null=True, verbose_name="check-out time"
                    ),
                ),
                (
                    "work_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total hours worked for the day, computed from check-in / check-out.",
                        max_digits=5,
                        null=True,
                        verbose_name="work hours",
                    ),
                ),
                (
                    "late_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minutes the employee arrived after the scheduled check-in time.",
                        verbose_name="late minutes",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="employee.employee",
                        verbose_name="employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "ordering": ("-date",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "date"),
                        name="unique_employee_date_attendance",
                    )
                ],
            },
        ),
    ]
