# Generated by Django 6.0.2 on 2026-03-06 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "pay_grade",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="pay grade"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="IDR", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("weekly", "Weekly"),
                            ("bi_weekly", "Bi-Weekly"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="frequency",
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="effective date")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salaries",
                        to="employee.employee",
                        verbose_name="employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "salary",
                "verbose_name_plural": "salaries",
                "ordering": ["-effective_date"],
            },
        ),
    ]
