# Generated by Django 6.0.2 on 2026-03-06 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "relationship",
                    models.CharField(max_length=50, verbose_name="relationship"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="phone number"),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="address"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="employee.employee",
                        verbose_name="employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "emergency contact",
                "verbose_name_plural": "emergency contacts",
                "ordering": ["name"],
            },
        ),
    ]
