# Generated by Django 6.0.2 on 2026-03-02 07:46

import config.roles
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ceo", "Ceo"),
                            ("cfo", "Cfo"),
                            ("coo", "Coo"),
                            ("cto", "Cto"),
                            ("director", "Director"),
                            ("vice_president", "Vice President"),
                            ("general_manager", "General Manager"),
                            ("manager", "Manager"),
                            ("supervisor", "Supervisor"),
                            ("team_lead", "Team Lead"),
                            ("hr_manager", "Hr Manager"),
                            ("hr_officer", "Hr Officer"),
                            ("recruiter", "Recruiter"),
                            ("payroll_officer", "Payroll Officer"),
                            ("finance_manager", "Finance Manager"),
                            ("accountant", "Accountant"),
                            ("finance_analyst", "Finance Analyst"),
                            ("auditor", "Auditor"),
                            ("administrator", "Administrator"),
                            ("it_manager", "It Manager"),
                            ("developer", "Developer"),
                            ("system_analyst", "System Analyst"),
                            ("it_support", "It Support"),
                            ("office_manager", "Office Manager"),
                            ("executive_assistant", "Executive Assistant"),
                            ("receptionist", "Receptionist"),
                            ("clerk", "Clerk"),
                            ("sales_manager", "Sales Manager"),
                            ("sales_representative", "Sales Representative"),
                            ("marketing_specialist", "Marketing Specialist"),
                            ("operations_manager", "Operations Manager"),
                            ("logistics_coordinator", "Logistics Coordinator"),
                            ("inventory_controller", "Inventory Controller"),
                            ("safety_officer", "Safety Officer"),
                            ("security_officer", "Security Officer"),
                            ("staff", "Staff"),
                            ("intern", "Intern"),
                            ("contractor", "Contractor"),
                            ("part_time", "Part Time"),
                        ],
                        default=config.roles.Role["STAFF"],
                        max_length=50,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
