# Generated by Django 6.0.2 on 2026-03-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emergencycontact",
            options={
                "ordering": ("-is_primary", "name"),
                "verbose_name": "Emergency Contact",
                "verbose_name_plural": "Emergency Contacts",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ("last_name", "first_name"),
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("spouse", "Spouse"),
                    ("parent", "Parent"),
                    ("relative", "Relative"),
                    ("colleague", "Colleague"),
                    ("other", "Other"),
                ],
                max_length=30,
                verbose_name="relationship",
            ),
        ),
    ]
