# Generated by Django 6.0.2 on 2026-03-10 17:44

import applications.imports.constants
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('import_type', models.CharField(choices=[('employee', 'Employee'), ('emergency_contact', 'Emergency Contact'), ('employment', 'Employment'), ('contract', 'Contract'), ('salary', 'Salary'), ('department', 'Department'), ('job_title', 'Job Title')], max_length=30, verbose_name='import type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('mapping', 'Mapping'), ('ready', 'Ready'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], db_index=True, default=applications.imports.constants.ImportStatus['PENDING'], max_length=20, verbose_name='status')),
                ('file', models.FileField(upload_to='imports/', verbose_name='file')),
                ('file_name', models.CharField(max_length=255, verbose_name='original file name')),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=10, verbose_name='file type')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='total rows')),
                ('processed_rows', models.PositiveIntegerField(default=0, verbose_name='processed rows')),
                ('success_rows', models.PositiveIntegerField(default=0, verbose_name='success rows')),
                ('failed_rows', models.PositiveIntegerField(default=0, verbose_name='failed rows')),
                ('field_mapping', models.JSONField(blank=True, null=True, verbose_name='field mapping')),
                ('error_summary', models.TextField(blank=True, verbose_name='error summary')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Import Job',
                'verbose_name_plural': 'Import Jobs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('row_number', models.PositiveIntegerField(verbose_name='row number')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('skipped', 'Skipped')], db_index=True, max_length=10, verbose_name='status')),
                ('raw_data', models.JSONField(verbose_name='raw data')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='imports.importjob', verbose_name='import job')),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logs',
                'ordering': ('row_number',),
            },
        ),
    ]
