# Generated by Django 6.0.2 on 2026-03-10 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='company name')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='legal name')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='tax ID')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='registration number')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='industry')),
                ('founded', models.CharField(blank=True, max_length=10, verbose_name='founded year')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo/', verbose_name='logo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter / X')),
                ('address_street', models.CharField(blank=True, max_length=255, verbose_name='street address')),
                ('address_city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('address_state', models.CharField(blank=True, max_length=100, verbose_name='state / province')),
                ('address_postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('address_country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('work_hours_per_week', models.PositiveSmallIntegerField(default=40, verbose_name='work hours per week')),
                ('probation_days', models.PositiveSmallIntegerField(default=90, verbose_name='probation period (days)')),
                ('annual_leave_days', models.PositiveSmallIntegerField(default=12, verbose_name='annual leave days')),
                ('sick_leave_days', models.PositiveSmallIntegerField(default=12, verbose_name='sick leave days')),
                ('default_currency', models.CharField(default='IDR', max_length=10, verbose_name='default currency')),
                ('payroll_cycle', models.CharField(default='monthly', max_length=30, verbose_name='payroll cycle')),
                ('employee_id_format', models.CharField(default='EMP-{YEAR}-{SEQ:04d}', help_text='Use {YEAR} and {SEQ:04d} as placeholders.', max_length=50, verbose_name='employee ID format')),
                ('timezone', models.CharField(default='Asia/Jakarta', max_length=50, verbose_name='timezone')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
            },
        ),
    ]
